name: Dar la hora
run-name: Â¡Estoy Calculando el tiempooo!
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
    inputs:
      alerta: 
        description: 'Nivel'
        required: true
        default: medio
        type: choice
        options:
          - bajo
          - medio
          - alto
      tags:
        description: 'Opcional'
        required: true
        type: string
jobs: 
  print-hola:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Correr Script para imprimir hora
        run: python hora.py
